#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=zalari@light-pi
readonly TARGET_PATH=/home/zalari/dmx-osc-bridge
readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/dmx-osc-bridge

docker build -t dmx-osc-bridge-builder .
docker run --rm -v "$(pwd)":/usr/src/bridge -w /usr/src/bridge dmx-osc-bridge-builder cargo build --release --target=${TARGET_ARCH}

rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} sudo systemctl restart dmx-osc-bridge-builder.sevice

